image: Visual Studio 2022
environment:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build_script:
- dotnet build src/JsonToResX.sln --configuration Release
test_script:
- dotnet test src/JsonToResX.sln --configuration Release --no-build --verbosity normal
artifacts:
- path: ./*.nupkg
